### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [yldylg/wifuick#1]
Hello Sir. I'm a UI/UX and Graphics Designer. I'm happy to see a new open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks before.

**Comment by yldylg** [comment]
Thank you. This is only a personal project and a professional logo is not essential. But it well be better if a logo is provided.

**Comment by yldylg** [comment]
Thank you. This is only a personal project and a professional logo is not essential. But it well be better if a logo is provided.

**Comment by yldylg** [comment]
@anharismail Thank you. This is only a personal project and a professional logo is not essential. But it well be better if a logo is provided.

**Comment by anharismail** [comment]
Hello, Sir @yldylg . These are my logo proposal for your project.
This logo was inspired by wifi and tools. I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.

I'll provide all file types and sizes you needed.

Hope you like it :)

### Version 1
![wifuick ver 1](https://user-images.githubusercontent.com/37614260/42024095-a273e64e-7aeb-11e8-9a5b-8abc4f001ee9.png)

### Version 2
![wifuick ver 2](https://user-images.githubusercontent.com/37614260/42024122-abc285ca-7aeb-11e8-9369-2dec133a013d.png)

**Comment by anharismail** [comment]
Hi @yldylg , is there any response to my logo proposal?

**Comment by yldylg** [comment]
@anharismail Your logo is very good. Thank you sir.

**Comment by anharismail** [comment]
What version do you prefer? @yldylg 

Can I put on readme and repositories as a pull request?

**Comment by yldylg** [comment]
@anharismail I prefer version 1. You can do what you want to do.

**Comment by anharismail** [comment]
Thanks for your response @yldylg , I'll pull a request about it
